# Site settings
title: Octocat's homepage
email: pmoyo@diginav.co
description: >-
  Bookmark this to keep an eye on my project updates!
url: "https://profmox.github.io"
baseurl: ""
github_username: profmox

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
